// Generated by gencpp from file sriforcesensor/ForceTorquePosition.msg
// DO NOT EDIT!


#ifndef SRIFORCESENSOR_MESSAGE_FORCETORQUEPOSITION_H
#define SRIFORCESENSOR_MESSAGE_FORCETORQUEPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>
#include <std_msgs/Float64MultiArray.h>

namespace sriforcesensor
{
template <class ContainerAllocator>
struct ForceTorquePosition_
{
  typedef ForceTorquePosition_<ContainerAllocator> Type;

  ForceTorquePosition_()
    : Forcevalue()
    , Radius()  {
    }
  ForceTorquePosition_(const ContainerAllocator& _alloc)
    : Forcevalue(_alloc)
    , Radius(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _Forcevalue_type;
  _Forcevalue_type Forcevalue;

   typedef  ::std_msgs::Float64MultiArray_<ContainerAllocator>  _Radius_type;
  _Radius_type Radius;





  typedef boost::shared_ptr< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> const> ConstPtr;

}; // struct ForceTorquePosition_

typedef ::sriforcesensor::ForceTorquePosition_<std::allocator<void> > ForceTorquePosition;

typedef boost::shared_ptr< ::sriforcesensor::ForceTorquePosition > ForceTorquePositionPtr;
typedef boost::shared_ptr< ::sriforcesensor::ForceTorquePosition const> ForceTorquePositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sriforcesensor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sriforcesensor': ['/home/zhong/Sensor/src/sriforcesensor/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b109b108f2bbaf48766fe7d3d50d6ee5";
  }

  static const char* value(const ::sriforcesensor::ForceTorquePosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb109b108f2bbaf48ULL;
  static const uint64_t static_value2 = 0x766fe7d3d50d6ee5ULL;
};

template<class ContainerAllocator>
struct DataType< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sriforcesensor/ForceTorquePosition";
  }

  static const char* value(const ::sriforcesensor::ForceTorquePosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist Forcevalue\n\
std_msgs/Float64MultiArray Radius\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
================================================================================\n\
MSG: std_msgs/Float64MultiArray\n\
# Please look at the MultiArrayLayout message definition for\n\
# documentation on all multiarrays.\n\
\n\
MultiArrayLayout  layout        # specification of data layout\n\
float64[]         data          # array of data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayLayout\n\
# The multiarray declares a generic multi-dimensional array of a\n\
# particular data type.  Dimensions are ordered from outer most\n\
# to inner most.\n\
\n\
MultiArrayDimension[] dim # Array of dimension properties\n\
uint32 data_offset        # padding elements at front of data\n\
\n\
# Accessors should ALWAYS be written in terms of dimension stride\n\
# and specified outer-most dimension first.\n\
# \n\
# multiarray(i,j,k) = data[data_offset + dim_stride[1]*i + dim_stride[2]*j + k]\n\
#\n\
# A standard, 3-channel 640x480 image with interleaved color channels\n\
# would be specified as:\n\
#\n\
# dim[0].label  = \"height\"\n\
# dim[0].size   = 480\n\
# dim[0].stride = 3*640*480 = 921600  (note dim[0] stride is just size of image)\n\
# dim[1].label  = \"width\"\n\
# dim[1].size   = 640\n\
# dim[1].stride = 3*640 = 1920\n\
# dim[2].label  = \"channel\"\n\
# dim[2].size   = 3\n\
# dim[2].stride = 3\n\
#\n\
# multiarray(i,j,k) refers to the ith row, jth column, and kth channel.\n\
\n\
================================================================================\n\
MSG: std_msgs/MultiArrayDimension\n\
string label   # label of given dimension\n\
uint32 size    # size of given dimension (in type units)\n\
uint32 stride  # stride of given dimension\n\
";
  }

  static const char* value(const ::sriforcesensor::ForceTorquePosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Forcevalue);
      stream.next(m.Radius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ForceTorquePosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sriforcesensor::ForceTorquePosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sriforcesensor::ForceTorquePosition_<ContainerAllocator>& v)
  {
    s << indent << "Forcevalue: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.Forcevalue);
    s << indent << "Radius: ";
    s << std::endl;
    Printer< ::std_msgs::Float64MultiArray_<ContainerAllocator> >::stream(s, indent + "  ", v.Radius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRIFORCESENSOR_MESSAGE_FORCETORQUEPOSITION_H
