// Generated by gencpp from file motor_arduino/Limit.msg
// DO NOT EDIT!


#ifndef MOTOR_ARDUINO_MESSAGE_LIMIT_H
#define MOTOR_ARDUINO_MESSAGE_LIMIT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_arduino
{
template <class ContainerAllocator>
struct Limit_
{
  typedef Limit_<ContainerAllocator> Type;

  Limit_()
    : limit_number(0)
    , limit_start(false)  {
    }
  Limit_(const ContainerAllocator& _alloc)
    : limit_number(0)
    , limit_start(false)  {
  (void)_alloc;
    }



   typedef int16_t _limit_number_type;
  _limit_number_type limit_number;

   typedef uint8_t _limit_start_type;
  _limit_start_type limit_start;





  typedef boost::shared_ptr< ::motor_arduino::Limit_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_arduino::Limit_<ContainerAllocator> const> ConstPtr;

}; // struct Limit_

typedef ::motor_arduino::Limit_<std::allocator<void> > Limit;

typedef boost::shared_ptr< ::motor_arduino::Limit > LimitPtr;
typedef boost::shared_ptr< ::motor_arduino::Limit const> LimitConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_arduino::Limit_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_arduino::Limit_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace motor_arduino

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'motor_arduino': ['/home/zhong/Sensor/src/motor_arduino/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::motor_arduino::Limit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_arduino::Limit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_arduino::Limit_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_arduino::Limit_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_arduino::Limit_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_arduino::Limit_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_arduino::Limit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e1063a34d7b440da198356c0d16d8c89";
  }

  static const char* value(const ::motor_arduino::Limit_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe1063a34d7b440daULL;
  static const uint64_t static_value2 = 0x198356c0d16d8c89ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_arduino::Limit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_arduino/Limit";
  }

  static const char* value(const ::motor_arduino::Limit_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_arduino::Limit_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 limit_number\n\
bool limit_start\n\
";
  }

  static const char* value(const ::motor_arduino::Limit_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_arduino::Limit_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.limit_number);
      stream.next(m.limit_start);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Limit_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_arduino::Limit_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_arduino::Limit_<ContainerAllocator>& v)
  {
    s << indent << "limit_number: ";
    Printer<int16_t>::stream(s, indent + "  ", v.limit_number);
    s << indent << "limit_start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.limit_start);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_ARDUINO_MESSAGE_LIMIT_H
