# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from motor_arduino/stepper.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class stepper(genpy.Message):
  _md5sum = "418c9f364f01d80c862df03ea60e9515"
  _type = "motor_arduino/stepper"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 stepper_number
bool stepper_direction
int16 stepper_count
"""
  __slots__ = ['stepper_number','stepper_direction','stepper_count']
  _slot_types = ['int16','bool','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       stepper_number,stepper_direction,stepper_count

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(stepper, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.stepper_number is None:
        self.stepper_number = 0
      if self.stepper_direction is None:
        self.stepper_direction = False
      if self.stepper_count is None:
        self.stepper_count = 0
    else:
      self.stepper_number = 0
      self.stepper_direction = False
      self.stepper_count = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_hBh().pack(_x.stepper_number, _x.stepper_direction, _x.stepper_count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.stepper_number, _x.stepper_direction, _x.stepper_count,) = _get_struct_hBh().unpack(str[start:end])
      self.stepper_direction = bool(self.stepper_direction)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_hBh().pack(_x.stepper_number, _x.stepper_direction, _x.stepper_count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 5
      (_x.stepper_number, _x.stepper_direction, _x.stepper_count,) = _get_struct_hBh().unpack(str[start:end])
      self.stepper_direction = bool(self.stepper_direction)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_hBh = None
def _get_struct_hBh():
    global _struct_hBh
    if _struct_hBh is None:
        _struct_hBh = struct.Struct("<hBh")
    return _struct_hBh
