// Generated by gencpp from file sensor_arduino/WriteVoltage.msg
// DO NOT EDIT!


#ifndef SENSOR_ARDUINO_MESSAGE_WRITEVOLTAGE_H
#define SENSOR_ARDUINO_MESSAGE_WRITEVOLTAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sensor_arduino
{
template <class ContainerAllocator>
struct WriteVoltage_
{
  typedef WriteVoltage_<ContainerAllocator> Type;

  WriteVoltage_()
    : voltage()  {
    }
  WriteVoltage_(const ContainerAllocator& _alloc)
    : voltage(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _voltage_type;
  _voltage_type voltage;





  typedef boost::shared_ptr< ::sensor_arduino::WriteVoltage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sensor_arduino::WriteVoltage_<ContainerAllocator> const> ConstPtr;

}; // struct WriteVoltage_

typedef ::sensor_arduino::WriteVoltage_<std::allocator<void> > WriteVoltage;

typedef boost::shared_ptr< ::sensor_arduino::WriteVoltage > WriteVoltagePtr;
typedef boost::shared_ptr< ::sensor_arduino::WriteVoltage const> WriteVoltageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sensor_arduino::WriteVoltage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sensor_arduino::WriteVoltage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sensor_arduino

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_arduino': ['/home/zhong/Sensor/src/sensor_arduino/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sensor_arduino::WriteVoltage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sensor_arduino::WriteVoltage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_arduino::WriteVoltage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sensor_arduino::WriteVoltage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_arduino::WriteVoltage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sensor_arduino::WriteVoltage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sensor_arduino::WriteVoltage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8343d456b6f735c9321e0caae0e82981";
  }

  static const char* value(const ::sensor_arduino::WriteVoltage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8343d456b6f735c9ULL;
  static const uint64_t static_value2 = 0x321e0caae0e82981ULL;
};

template<class ContainerAllocator>
struct DataType< ::sensor_arduino::WriteVoltage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sensor_arduino/WriteVoltage";
  }

  static const char* value(const ::sensor_arduino::WriteVoltage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sensor_arduino::WriteVoltage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16[] voltage\n\
";
  }

  static const char* value(const ::sensor_arduino::WriteVoltage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sensor_arduino::WriteVoltage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WriteVoltage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sensor_arduino::WriteVoltage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sensor_arduino::WriteVoltage_<ContainerAllocator>& v)
  {
    s << indent << "voltage[]" << std::endl;
    for (size_t i = 0; i < v.voltage.size(); ++i)
    {
      s << indent << "  voltage[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.voltage[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SENSOR_ARDUINO_MESSAGE_WRITEVOLTAGE_H
